import { expect, test } from '@playwright/test'

/**
 * Cross-tenant isolation harness.
 *
 * These tests sign in as a user inside Tenant A and then try to reach
 * URLs / actions owned by Tenant B. Every assertion is that the
 * attempt fails (404 or 403) — a green suite is the guarantee that
 * the RLS + query filters keep the walls up.
 *
 * Almost every real test lives in the placeholder below and stays
 * skipped while `TENANCY_ENABLED` is falsy. As each phase lands, the
 * matching probe (courses, stats, certificates, org board, …) gets
 * un-skipped and pointed at real tenant/URL pairs.
 *
 * Auth: eventually two dedicated storage-state files
 * (`.auth/tenant-a.json`, `.auth/tenant-b.json`) generated by
 * auth.setup.ts. Not wired yet — Phase 1 creates the seed tenants
 * and Phase 3 wires the setup step.
 */

const TENANCY_ENABLED = process.env.TENANCY_ENABLED === '1'

test.describe('Cross-tenant isolation', () => {
  test.skip(
    !TENANCY_ENABLED,
    'Multi-tenancy is disabled on this deploy (TENANCY_ENABLED != 1)',
  )

  // Placeholder to ensure the suite compiles + is discoverable by CI
  // while tenancy is still building. Once Phase 1 lands and we have
  // two seed tenants, real probes replace this.
  test.fixme(
    'Tenant A cannot see Tenant B courses',
    async ({ page: _page }) => {
      // await page.goto(`/admin/courses/${tenantBCourseSlug}`)
      // await expect(page).toHaveURL(/\/404|\/dashboard/)
      expect(true).toBe(true)
    },
  )

  test.fixme(
    'Tenant A cannot enrol into Tenant B course by ID',
    async ({ page: _page }) => {
      expect(true).toBe(true)
    },
  )

  test.fixme(
    'Tenant A cannot list Tenant B members / staff',
    async ({ page: _page }) => {
      expect(true).toBe(true)
    },
  )

  test.fixme(
    'Tenant A cannot view Tenant B stat metrics or data points',
    async ({ page: _page }) => {
      expect(true).toBe(true)
    },
  )

  test.fixme(
    'Tenant A cannot download Tenant B certificates via signed URL',
    async ({ page: _page }) => {
      expect(true).toBe(true)
    },
  )

  test.fixme(
    'Tenant A cannot fetch Tenant B org board revisions',
    async ({ page: _page }) => {
      expect(true).toBe(true)
    },
  )

  test.fixme(
    'Super-admin can enter Tenant B while cookie active-company was Tenant A',
    async ({ page: _page }) => {
      expect(true).toBe(true)
    },
  )
})
