import type { Enrollment, User } from "./types"

export const currentAdmin: User = {
  id: "u-admin",
  email: "keanu@legacyscale.co",
  name: "Keanu Vasquez",
  role: "ADMIN",
  isActive: true,
  emailVerified: true,
  lastLoginAt: "2026-05-27T08:14:00Z",
  createdAt: "2025-11-02",
}

export const currentMember: User = {
  id: "u-001",
  email: "marcus.lee@gmail.com",
  name: "Marcus Lee",
  role: "MEMBER",
  isActive: true,
  emailVerified: true,
  lastLoginAt: "2026-05-27T07:02:00Z",
  createdAt: "2026-01-15",
}

export const members: User[] = [
  currentMember,
  {
    id: "u-002",
    email: "sofia.reyes@outlook.com",
    name: "Sofia Reyes",
    role: "MEMBER",
    isActive: true,
    emailVerified: true,
    lastLoginAt: "2026-05-26T19:40:00Z",
    createdAt: "2026-01-20",
  },
  {
    id: "u-003",
    email: "david.okafor@gmail.com",
    name: "David Okafor",
    role: "MEMBER",
    isActive: true,
    emailVerified: true,
    lastLoginAt: "2026-05-27T06:11:00Z",
    createdAt: "2026-02-04",
  },
  {
    id: "u-004",
    email: "amara.singh@proton.me",
    name: "Amara Singh",
    role: "MEMBER",
    isActive: true,
    emailVerified: false,
    lastLoginAt: "2026-05-24T13:25:00Z",
    createdAt: "2026-02-18",
  },
  {
    id: "u-005",
    email: "liam.connor@gmail.com",
    name: "Liam Connor",
    role: "MEMBER",
    isActive: false,
    emailVerified: true,
    lastLoginAt: "2026-04-30T10:00:00Z",
    createdAt: "2026-01-08",
  },
  {
    id: "u-006",
    email: "grace.tan@gmail.com",
    name: "Grace Tan",
    role: "ADMIN",
    isActive: true,
    emailVerified: true,
    lastLoginAt: "2026-05-27T05:50:00Z",
    createdAt: "2025-12-01",
  },
  {
    id: "u-007",
    email: "noah.bennett@gmail.com",
    name: "Noah Bennett",
    role: "MEMBER",
    isActive: true,
    emailVerified: true,
    lastLoginAt: "2026-05-25T22:13:00Z",
    createdAt: "2026-03-09",
  },
  {
    id: "u-008",
    email: "isabella.cruz@gmail.com",
    name: "Isabella Cruz",
    role: "MEMBER",
    isActive: true,
    emailVerified: true,
    createdAt: "2026-05-26T16:30:00Z",
  },
]

export function findMember(id: string): User | undefined {
  return members.find((m) => m.id === id)
}

export const enrollments: Enrollment[] = [
  {
    id: "e-001",
    user: { id: "u-001", name: "Marcus Lee", email: "marcus.lee@gmail.com" },
    course: { id: "course-1", title: "7-Figure Agency Program" },
    status: "ACTIVE",
    source: "GHL_WEBHOOK",
    progressPercent: 38,
    enrolledAt: "2026-01-15",
    lastAccessedAt: "2026-05-27T07:02:00Z",
    expiresAt: null,
  },
  {
    id: "e-002",
    user: { id: "u-002", name: "Sofia Reyes", email: "sofia.reyes@outlook.com" },
    course: { id: "course-1", title: "7-Figure Agency Program" },
    status: "ACTIVE",
    source: "GHL_WEBHOOK",
    progressPercent: 72,
    enrolledAt: "2026-01-20",
    lastAccessedAt: "2026-05-26T19:40:00Z",
    expiresAt: null,
  },
  {
    id: "e-003",
    user: { id: "u-003", name: "David Okafor", email: "david.okafor@gmail.com" },
    course: { id: "course-2", title: "Client Acquisition Mastery" },
    status: "ACTIVE",
    source: "SELF_ENROLL",
    progressPercent: 21,
    enrolledAt: "2026-02-04",
    lastAccessedAt: "2026-05-27T06:11:00Z",
    expiresAt: "2027-02-04",
  },
  {
    id: "e-004",
    user: { id: "u-004", name: "Amara Singh", email: "amara.singh@proton.me" },
    course: { id: "course-1", title: "7-Figure Agency Program" },
    status: "PENDING",
    source: "ADMIN",
    progressPercent: 0,
    enrolledAt: "2026-02-18",
    expiresAt: null,
  },
  {
    id: "e-005",
    user: { id: "u-005", name: "Liam Connor", email: "liam.connor@gmail.com" },
    course: { id: "course-1", title: "7-Figure Agency Program" },
    status: "REVOKED",
    source: "MANUAL",
    progressPercent: 14,
    enrolledAt: "2026-01-08",
    expiresAt: null,
    revokedReason: "Refund requested",
  },
  {
    id: "e-006",
    user: { id: "u-007", name: "Noah Bennett", email: "noah.bennett@gmail.com" },
    course: { id: "course-3", title: "High-Ticket Sales System" },
    status: "EXPIRED",
    source: "GHL_WEBHOOK",
    progressPercent: 96,
    enrolledAt: "2025-05-09",
    expiresAt: "2026-05-09",
  },
  {
    id: "e-007",
    user: { id: "u-002", name: "Sofia Reyes", email: "sofia.reyes@outlook.com" },
    course: { id: "course-3", title: "High-Ticket Sales System" },
    status: "ACTIVE",
    source: "SELF_ENROLL",
    progressPercent: 55,
    enrolledAt: "2026-03-19",
    lastAccessedAt: "2026-05-25T11:02:00Z",
    expiresAt: null,
  },
]
